AoE = "Area of Effect"
AoEs = "Areas of Effect"
omen = "A puddle telegraphing an upcoming AoE"
Omen = "A puddle telegraphing an upcoming AoE"
omens = "Puddle telegraphing an upcoming AoE"
Omens = "Puddle telegraphing an upcoming AoE"
"principal direction" = "Cardinal or intercardinal"
"Principal direction" = "Cardinal or intercardinal"
"principal directions" = "Cardinals or intercardinals"
"Principal directions" = "Cardinals or intercardinals"

"stack" = "An attack that shares damage among all the players hit"
"Stack" = "An attack that shares damage among all the players hit"
"stacks" = "Attacks that shares damage among all the players hit"
"Stacks" = "Attacks that shares damage among all the players hit"
"pair stack" = "A shared-damage stack meant for 2 players"
"Pair stack" = "A shared-damage stack meant for 2 players"
"pair stacks" = "Shared-damage stacks meant for 2 players"
"Pair stacks" = "Shared-damage stacks meant for 2 players"
"LP stack" = "A shared-damage stack meant for a light party, i.e. 4 players"
"LP stacks" = "Shared-damage stacks meant for a light party, i.e. 4 players"
"full-party stack" = "A shared-damage stack meant for the entire party"
"Full-party stack" = "A shared-damage stack meant for the entire party"

E8S = "Eden's Verse: Refulgence (Savage)"
E11S = "Eden's Promise: Anamorphosis (Savage)"
E12S = "Eden's Promise: Eternity (Savage)"